{% set name = "bfg" %}
{% set version = "1.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://repo1.maven.org/maven2/com/madgag/{{ name }}/{{ version }}/{{ name }}-{{ version }}.jar
  sha256: dfe2885adc2916379093f02a80181200536856c9a987bf21c492e452adefef7a

build:
  number: 0

requirements:
  run:
    - openjdk >=8

test:
  commands:
    - bfg | grep "{{ version }}"  # [not win]
    - bfg | findstr /c:"{{ version }}"  # [win]

about:
  home: https://rtyley.github.io/bfg-repo-cleaner/
  summary: BFG Repo-Cleaner
  license: GPL-3.0-only
  license_file: LICENSE
  license_family: GPL
  doc_url: https://rtyley.github.io/bfg-repo-cleaner/
  dev_url: https://github.com/rtyley/bfg-repo-cleaner/

extra:
  recipe-maintainers:
    - carlodri
    - janjagusch
