{% set name = "bfg" %}
{% set version = "1.13.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://repo1.maven.org/maven2/com/madgag/{{ name }}/{{ version }}/{{ name }}-{{ version }}.jar
  sha256: bf22bab9dd42d4682b490d6bc366afdad6c3da99f97521032d3be8ba7526c8ce
  
build:
  number: 2

requirements:
  run:
    - openjdk >=8

test:
  commands:
    - bfg

about:
  home: https://rtyley.github.io/bfg-repo-cleaner/
  summary: 'BFG Repo-Cleaner'
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  doc_url: https://rtyley.github.io/bfg-repo-cleaner/
  dev_url: https://github.com/rtyley/bfg-repo-cleaner/

extra:
  recipe-maintainers:
    - JohnGreeley
    - carlodri
