{% set name = "bfg" %}
{% set version = "1.14.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://repo1.maven.org/maven2/com/madgag/{{ name }}/{{ version }}/{{ name }}-{{ version }}.jar
  sha256: 1a75e9390541f4b55d9c01256b361b815c1e0a263e2fb3d072b55c2911ead0b7

build:
  number: 1

requirements:
  run:
    - openjdk >=8

test:
  commands:
    - bfg | grep "{{ version }}"  # [not win]
    - bfg | findstr /c:"{{ version }}"  # [win]

about:
  home: https://rtyley.github.io/bfg-repo-cleaner/
  summary: BFG Repo-Cleaner
  license: GPL-3.0-only
  license_file: LICENSE
  license_family: GPL
  doc_url: https://rtyley.github.io/bfg-repo-cleaner/
  dev_url: https://github.com/rtyley/bfg-repo-cleaner/

extra:
  recipe-maintainers:
    - carlodri
    - janjagusch
